### ISSUE TITLE
Geekshed Bug

### ISSUE THREAD

**Issue by HeyMan7** [Liamraystanley/Code#82] opened 2014-12-24 07:19 UTC
Whenever I start or restart the bot, it shows this error in console:
http://paste.ml/yeji.rb

It doesn't seem to affect anything.

I'm connecting to irc.geekshed.net:6667
Channel is #tfoccentral

**Comment by Liamraystanley** [comment] 2015-01-04 04:37
As of now, I am unable to reproduce this issue. Closing, as there may have been other intermittent issues in play here.

**Closed by Liamraystanley** 2015-01-04 04:37 UTC
Labels: bug
